#!/bin/sh

export CHROME_DEVEL_SANDBOX=/usr/sbin/chrome-devel-sandbox
export LD_LIBRARY_PATH=/usr/lib/chromium

export GOOGLE_API_KEY=" "
export GOOGLE_DEFAULT_CLIENT_ID=" "
export GOOGLE_DEFAULT_CLIENT_SECRET=" "

CHROME_EXTRA_ARGS="--use-gl=egl --gpu-no-context-lost --ignore-gpu-blacklist --enable-gpu-rasterization --enable-native-gpu-memory-buffers --disable-gpu-compositing"

if [ "`whoami`" = "root" ] ; then
	CHROME_EXTRA_ARGS="${CHROME_EXTRA_ARGS} --user-data-dir=ROOT_HOME/.chromium/"
fi

/usr/bin/chromium/chrome ${CHROME_EXTRA_ARGS} $@
